import { Inter } from "next/font/google";
import "./globals.css";
import Spline from "@splinetool/react-spline/next";
import Navbar from "../components/Navbar/Navbar";
import Userbar from "../components/Userbar/Userbar";
import style from "./layout.module.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />

                <Userbar />
                <main className={style.panel}>{children}</main>

                <Spline
                    scene="https://prod.spline.design/1IbTsvj9GRHhGa6P/scene.splinecode"
                    width={"100%"}
                    height={"100%"}
                    className={style.character}
                />
            </body>
        </html>
    );
}
